# -*- coding: utf-8 -*-
"""Customer Engagement & Product Utilization Analytics for Retention Strategy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wEmrzZNVFpLC8i7mb_ALQqLXLipYP-9W

## ***Customer Engagement & Product Utilization Analytics for Retention Strategy***

### ***Task 1. Data Ingestion & Validation***
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Load dataset
data = pd.read_excel('/content/European Bank.xlsx')

#Take a brief look at the data. Display the 1st 5 rows
data.head()

import pandas as pd

#Load dataset (added to resolve NameError)
data = pd.read_excel('/content/European Bank.xlsx')

#Read dimensions
data.shape
#Read row names
data.index
#Read column names
data.columns
#Read basic information
data.info()

#Mean of "IsActiveMember"

data['IsActiveMember'].mean()

#Mean of "NumOfProducts"

data['NumOfProducts'].mean()

#Count of data

data.count()

#Check the statistical range to find "impossible" numbers in Engagement and Product fields.

print("Statistical Range Check:")
#Correctly select the columns from the DataFrame and apply describe()
statistical_summary = data[['IsActiveMember', 'NumOfProducts']].describe()
print(statistical_summary)

#Output: The Range (Minimum and Maximum)

#Validate Engagement and Product Fields
#Check for missing values in 'IsActiveMember' and 'NumOfProducts'

print("Missing Values Check:")
print(data[['IsActiveMember', 'NumOfProducts']].isnull().sum())

#Output: Number of Missing Values

#Required fields SHOULD be binary

#Check Engagement and Product values are binary.

print("Binary Check:")
print('IsActiveMember')
print(data['IsActiveMember'].unique())
print('HasCrCard')
print(data['HasCrCard'].unique())

#Output: Confirming the Binary nature of Engagemnt and Product values

#Confirming Churn Labeling Accuracy in the dataset


inconsistent_data = data[(data['Exited'] == 0) & (data['NumOfProducts'] == 0)]

print("Number of inconsistent churn labels:")

print(inconsistent_data)

#If 0; "Not Churned" customers have products and are engaged. Ideal

"""### ***Task 2. Engagement Classification***"""

import pandas as pd

#Load dataset (assuming it's already defined elsewhere, or needs to be loaded here)
data = pd.read_excel('/content/European Bank.xlsx')

#Engagement Profiles - group customers based on behaviour
#Using "IsActiveMember", "NomOfProducts", "HasCrCard", "HasCrScore" and "Balance" to define the above.

#Create Engagement Profiles

# Initialize the 'EngagementProfile' column with a default value
data['EngagementProfile'] = 'Standard'

#1. Actively engaged customers (Elite): Active + Multiple Products (2+) + Credit Card Holder + High Credit Score (500+)

data.loc[(data['IsActiveMember'] == 1) & (data['NumOfProducts'] >= 2) & (data['HasCrCard'] == 1) & (data['CreditScore'] >= 500), 'EngagementProfile'] = 'Active engaged customers'

#2. Inactive Disengaged Customers: Not active + low product count + Has credit card + low credit score (<500)

data.loc[(data['IsActiveMember'] == 0) & (data['NumOfProducts'] == 1) & (data['HasCrCard'] == 0) & (data['CreditScore'] < 500), 'EngagementProfile'] = 'Inactive Disengaged Customers'

#3. Active low-product customers: Active + Low product count (=2) + Has Credit Card + High Credit Score (500+)

data.loc[(data['IsActiveMember'] == 1) & (data['NumOfProducts'] == 2) & (data['HasCrCard'] == 1) & (data['CreditScore'] >= 500), 'EngagementProfile'] = 'Active but low-product customers'

#4. Inactive high-balance customers

data.loc[(data['IsActiveMember'] == 0) & (data['Balance'] > 100000), 'EngagementProfile'] = 'Inactive high-balance customers'

#Print the distribution

print(data['EngagementProfile'].value_counts())

#Check if the classification predict churn or not.
#Churn rate (Mean of 'Exited' column); Proportion of customers who have churned/exited the bank

print(data.groupby('EngagementProfile') ['Exited'].mean())

#Visualtisation (Customer Volume by Engagement Profile)

#Set the visual style

sns.set_theme(style="darkgrid")
plt.figure(figsize=(18, 6))

#Plot 1: Distribution of Engagement Profiles (Volume)

plt.subplot(1, 2, 1)
order = data['EngagementProfile'].value_counts().index
sns.countplot(data=data, y='EngagementProfile', order=order, palette='viridis')
plt.title('Customer Volume by Engagement Profile', fontsize=14)
plt.xlabel('Number of Customers (Log Scale)')
plt.ylabel('Engagement Profile')
plt.xscale('log') # Apply logarithmic scale to the x-axis
plt.show()

##Visualtisation (Churn Rate by Engagement Profile)
#Set the visual style

sns.set_theme(style="darkgrid")
plt.figure(figsize=(16, 6))

#Plot 2: Churn Rate by Profile (Outcome)

plt.subplot(1,2,2)

#Calculate mean churn (Exited) for each group

churn_rate = data.groupby('EngagementProfile')['Exited'].mean().sort_values(ascending=False)
sns.barplot(x=churn_rate.values, y=churn_rate.index, palette='magma')
plt.title('Churn Rate by Engagement Profile', fontsize=14)
plt.xlabel('Percentage of Group Churned')
plt.ylabel('Churn Rate')
plt.xscale('log') # Apply logarithmic scale to the x-axis
plt.show()

"""### ***Task 3. Product Utilization Analysis***"""

#Churn rate by number of products
#Shows the churn rate corresponding to a specific count of products

Product_churn = data.groupby('NumOfProducts')['Exited'].mean().reset_index()
Product_churn.columns = ['NumOfProducts', 'ChurnRate']

print("   Churn Rate by Product Count   ")
print(Product_churn)

#Define Single product vs Multi product
#Creates a new category based on the number of products

data['Product_Type'] = 'Single Product'
data.loc[data['NumOfProducts'] > 1, 'Product_Type'] = 'Multi Product'

#Compares the retention (To Stay/Exist; Prevent from leaving) between the 2 groups

retention_comparison = data.groupby('Product_Type')['Exited'].mean().reset_index()
retention_comparison.columns = ['Product_Type', 'ChurnRate']

print("     Retention: Single vs Multi Product     ")
print(retention_comparison)

#Product depth vs churn relationship
#Shows how churn rate behaves as product depth changes

Product_churn = data.groupby('NumOfProducts')['Exited'].mean().reset_index()
Product_churn.columns = ['NumOfProducts', 'ChurnRate']

print("   Product Depth vs Churn Relationship   ")
print(Product_churn)

#Visualization of the relationship between number of products used by customers & their churn rate

plt.figure(figsize=(16, 6))
sns.barplot(data = Product_churn, x = 'NumOfProducts', y = 'ChurnRate', hue = 'NumOfProducts', palette='viridis', legend=False)
plt.title('Churn Rate by Number of Products')
plt.ylabel('Churn Rate (Mean)')
plt.show()

#Visualisation of Single-product vs multi-product retention

plt.figure(figsize=(16, 6))
sns.barplot(data = retention_comparison, x = 'Product_Type', y = 'ChurnRate', hue = 'Product_Type', palette='viridis', legend=False)
plt.title('Retention: Single vs Multi Product')
plt.ylabel('Churn Rate (Mean)')
plt.show()

#Visualization of the relationship between Product Depth & Churn Relationship

plt.figure(figsize=(16, 6))
sns.barplot(data = Product_churn, x = 'NumOfProducts', y = 'ChurnRate', hue = 'NumOfProducts', palette='viridis', legend=False)
plt.title('Product Depth vs Churn Relationship')
plt.ylabel('Churn Rate (Mean)')
plt.show()

"""### ***Task 4. Financial Commitment vs Engagement Analysis***"""

#Balance vs Activity Cross-Analysis
#Profile Stats (Cross-Analysis of Balance, Estimated Salary, Credit Score and Tenure by Activity Status)

#Grouping by 'Exited' and 'IsActiveMember' and looking at the average of the 4 financial variables
Finacial_Profile = data.groupby(['IsActiveMember'])[['Balance', 'EstimatedSalary', 'CreditScore', 'Tenure']].mean().reset_index()

print("Consumer Activity Status:")
print(Finacial_Profile)

#Visualization of the Balance vs Activity Cross-Analysis

plt.figure(figsize=(16, 6))
sns.barplot(data = Finacial_Profile, x = 'IsActiveMember', y = 'Balance', hue = 'IsActiveMember', palette='viridis', legend=False)
plt.title('Balance vs Activity Cross-Analysis')
plt.xlabel('IsActiveMember (0=No, 1=Yes)')
plt.ylabel('Average Balance')
plt.show()

#Salary-Balance Mismatch
#1. Define the "High Salary" & "Low Balance" thresholds.
#Use the top 25% of earners (75th percentile for salary)
salary_threshold = data['EstimatedSalary'].quantile(0.75)
balance_threshold = 1000
#Customers with less than 1000 in the bank

#2. Identify the Mismatch
#To find people whoo earn MORE than the threshold but keep LESS than the balance limit

data['Mismatch'] = (data['EstimatedSalary'] > salary_threshold) & (data['Balance'] < balance_threshold)

#3. Output
mismatch_count = data['Mismatch'].sum()
total_customers = len(data)
mismatch_percentage = (mismatch_count / total_customers) * 100

print("Salary-Balance Mismatch Results")
print(f"High Salary Threshold: {salary_threshold:.2f}")
print(f"Total Number of Customers: {total_customers}")
print(f"Number of Mismatched Customers: {mismatch_count}")
print(f"Percentage of Mismatched Customers: {mismatch_percentage:.2f}%")
print(f"Percentage of total base: {mismatch_count / total_customers * 100:.2f}%")


#$.Visualize
plt.figure(figsize=(16, 6)) # Corrected plt.fig to plt.figure
sns.scatterplot(data=data, x='EstimatedSalary', y='Balance', hue='Mismatch', palette={True:'green', False:'red'}, alpha = 0.4) # Removed quotes from alpha
plt.axvline(x=salary_threshold, color='black', linestyle='--', label = 'High Salary Threshold')
plt.axhline(y=balance_threshold, color='yellow', linestyle='--', label = 'Low Balance Threshold')
plt.title('Detction of Salary-Balance Mismatch (Red Points)')
plt.legend()
plt.show()

#Identification of “at-risk premium customers”
#1. Define the Premium Thresholds (limits)
premium_balance_threshold = 100000
premium_credit_score_threshold = 500

#2. Identify At-Risk Premium Customers
#Conditions: Inactive (0) & High Balance & High Credit Score

data['At_Risk_Premium'] = (data['IsActiveMember'] == 0) & (data['Balance'] > premium_balance_threshold) & (data['CreditScore'] > premium_credit_score_threshold)

#3. Output the numbers
premium_count = data['At_Risk_Premium'].sum()
total_inactive = (data['IsActiveMember'] == 0).sum()

print("Identification of At-Risk Premium Customer")
print('')
print(f"Number of Premium Customers at Risk: {premium_count}")
print('')
print(f'Percentage of all Inactive Customers: {premium_count / total_inactive * 100:.2f}%')
print('')

#View a sample of these specific customers
print("Sample of At-Risk Premium Customers:")
print('')
print(data[data['At_Risk_Premium'] == True] [['Balance', 'CreditScore', 'Tenure', 'EstimatedSalary']].head())

"""### ***Task 5. Retention Strength Assessment***"""

#1. Define the "Sticky Customer" Profile
#Active + 2 Products + High Credit Score
data['Sticky_Customer'] = (data['IsActiveMember'] == 1) & (data['NumOfProducts'] == 2) & (data['CreditScore'] >= 500)

print("Sticky Customer Profile")
print(data['Sticky_Customer'].value_counts())

#2. Measure Churn Stability across Engagement Tiers
#Compare the churn rate of "Sticky" customers vs the rest of the bank
retention_comparison = data.groupby('Sticky_Customer')['Exited'].mean().reset_index()
retention_comparison['Sticky_Indicator'] = retention_comparison['Sticky_Customer'].map({True: 'Sticky (Gold Standard)', False: 'General/At-Risk'})
retention_comparison.columns = ['Sticky_Customer', 'ChurnRate', 'Sticky_Indicator']


print("Churn Rate Comparison:")
print(retention_comparison)

#3. Identify the "Tensure Threshold" (When does a customer become stable?)
plt.figure(figsize=(16, 6))
sns.lineplot(data = data, x = 'Tenure', y = 'Exited', hue = 'IsActiveMember', marker = 'o', ci = None)
plt.axhline(data['Exited'].mean(), color = 'red', linestyle = '--', label = 'Bank Average Churn')
plt.title('Retention Thresholds: Tenure vs Probability of Exit')
plt.xlabel('Tenure')
plt.ylabel('Churn Rate')
plt.legend()
plt.grid(True, alpha = 0.3)
plt.show()